#ifndef standard_h
#define standard_h

// MODIFICARE QUESTI VALORI PER CAMBIARE I RISULTATI DESIDERATI
//TO DO!!
#define QUERYSIZE 1500 //QUERY_LEN
#define RESPONSESIZE 200 // RESPONSE_LEN
#define PRMTRSIZE 400 //PARAMETER_LEN
#define KEYSIZE 30 //KEY_LEN
#define VALUESIZE 30 //VALUE_LEN
#define MSGIDSIZE 30 //MESSAGE_ID_LEN

#define REDISSPACE "##" //SPACE_REDIS_STRING
#define BLANKSPACE " " //SPACE

#endif