#ifndef standard_h
#define standard_h

// MODIFICARE QUESTI VALORI PER CAMBIARE I RISULTATI DESIDERATI
//TO DO!!
#define QUERYSIZE 1500 //Query_len
#define RESPONSE_LEN 200 // RESPONSE_LEN
#define PARAMETERS_LEN 400 //PARAMETERS_LEN
#define KEY_LEN 30 //KEY_LEN
#define VALUESIZE 30 //VALUE_LEN
#define MSGIDSIZE 30 //MESSAGE_ID_LEN
#define SPACE_REDIS_STRING "##" //SPACE_REDIS_STRING
#define SPACE " " //SPACE

#endif